# Phase 0: Foundation — Networking, Storage & Secrets, IAM
# Phase 2: k3s cluster + SurrealDB
# Phases 3-6 modules are added here as each phase is implemented.

# ── SSH key pair for k3s EC2 access ──────────────────────────────────────────
# Private key stored in Secrets Manager; deploy.ps1 fetches it for SSH via EIC.

resource "tls_private_key" "k3s_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "k3s" {
  key_name   = "fintel-k3s-${var.env}"
  public_key = tls_private_key.k3s_ssh.public_key_openssh
}

resource "aws_secretsmanager_secret" "k3s_ssh_key" {
  name                    = "fintel/k3s-ssh-key-${var.env}"
  recovery_window_in_days = var.env == "staging" ? 0 : 30
  description             = "Private SSH key for k3s EC2 (${var.env}) — generated by Terraform"
}

resource "aws_secretsmanager_secret_version" "k3s_ssh_key" {
  secret_id     = aws_secretsmanager_secret.k3s_ssh_key.id
  secret_string = tls_private_key.k3s_ssh.private_key_pem
}

module "networking" {
  source = "./modules/networking"

  env                  = var.env
  aws_region           = var.aws_region
  vpc_cidr             = var.vpc_cidr
  private_subnet_cidrs = var.private_subnet_cidrs
  availability_zones   = var.availability_zones
  public_subnet_cidr   = var.public_subnet_cidr
}

module "storage" {
  source = "./modules/storage"

  env = var.env
}

module "iam" {
  source = "./modules/iam"

  env         = var.env
  github_repo = var.github_repo
}

# ── Phase 2: k3s cluster + SurrealDB ─────────────────────────────────────────

module "k3s" {
  source = "./modules/k3s"

  env                       = var.env
  aws_region                = var.aws_region
  instance_type             = var.ec2_instance_type
  ebs_volume_size_gb        = var.ebs_volume_size_gb
  subnet_id                 = module.networking.private_subnet_ids[0]
  sg_k3s_id                 = module.networking.sg_k3s_id
  ec2_instance_profile_name = module.iam.ec2_instance_profile_name
  ecr_repo_url              = module.storage.ecr_repo_url
  key_name                  = aws_key_pair.k3s.key_name
}
